#!/bin/bash

set -eu

# square header on top left, near the p1 writing
# list of gpios
# 01 3.3V 5V   02
#       0 5V
#       1 Gnd
#       4 14
#     Gnd 15
#      17 18
#      21 Gnd
#      22 23
#     3v3 24
#      10 Gnd
#       9 25
#      11 8
# 25  Gnd 7    26

PLAY=4
STOP=14
NEXT=15
PREV=17

RED=10
BLUE=9
GREEN=11
YELLOW=8

# init buttons
[ -d /sys/class/gpio/gpio${PLAY} ] || echo ${PLAY} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${STOP} ] || echo ${STOP} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${NEXT} ] || echo ${NEXT} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${PREV} ] || echo ${PREV} > /sys/class/gpio/export

echo out > /sys/class/gpio/gpio${PLAY}/direction
echo out > /sys/class/gpio/gpio${STOP}/direction
echo out > /sys/class/gpio/gpio${NEXT}/direction
echo out > /sys/class/gpio/gpio${PREV}/direction

# init leds
[ -d /sys/class/gpio/gpio${RED} ] || echo ${RED} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${BLUE} ] || echo ${BLUE} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${GREEN} ] || echo ${GREEN} > /sys/class/gpio/export
[ -d /sys/class/gpio/gpio${YELLOW} ] || echo ${YELLOW} > /sys/class/gpio/export

echo in > /sys/class/gpio/gpio${RED}/direction
echo in > /sys/class/gpio/gpio${BLUE}/direction
echo in > /sys/class/gpio/gpio${GREEN}/direction
echo in > /sys/class/gpio/gpio${YELLOW}/direction

base_dir="/home/pi/Music/Rusty Tea Makers - Show it to your Mother - 158273 --- Jamendo - MP3"
songs[0]="${base_dir}/01 - Rusty Tea Makers - Mirror.mp3"
songs[1]="${base_dir}/02 - Rusty Tea Makers - Summer.mp3"
songs[2]="${base_dir}/03 - Rusty Tea Makers - Monkeys Jumping.mp3"
songs[3]="${base_dir}/04 - Rusty Tea Makers - Lie in a Box.mp3"
songs[4]="${base_dir}/05 - Rusty Tea Makers - Man in Dress.mp3"
songs[5]="${base_dir}/06 - Rusty Tea Makers - I Need More.mp3"
songs[6]="${base_dir}/07 - Rusty Tea Makers - Hello.mp3"
songs[7]="${base_dir}/08 - Rusty Tea Makers - Show it to your Mother.mp3"

current_song=0
nb_songs=8
pid=0
period=.1 #100ms

function stop {
	kill -TERM ${pid}
	pid=0
	echo "stopped music"
}

function next {
	current_song=$((${current_song} + 1))
	if [ ${current_song} = ${nb_songs} ]; then
		current_song=0
	fi
	echo "current song is ${songs[${current_song}]}"
}

function prev {
	if [ ${current_song} = 0 ]; then
		current_song=$((${nb_songs} - 1))
	else
		current_song=$((${current_song} - 1))
	fi
	echo "current song is ${songs[${current_song}]}"
}

function play_song { # name collision
	echo "play ${songs[${current_song}]}"
	play "${songs[${current_song}]}" > /dev/null 2>&1 &
	pid=$!
	echo ${pid}
}

while [ 1 ]; do
	sleep ${period}

	# read buttons state
	play=$(cat /sys/class/gpio/gpio${PLAY}/value)
	stop=$(cat /sys/class/gpio/gpio${STOP}/value)
	next=$(cat /sys/class/gpio/gpio${NEXT}/value)
	prev=$(cat /sys/class/gpio/gpio${PREV}/value)

	if [ ${pid} = 0 ]; then
		if [ ${play} = 1 ]; then
			play_song
		fi
		if [ ${next} = 1 ]; then
			next
		fi
		if [ ${prev} = 1 ]; then
			prev
		fi
	else
		if [ ${stop} = 1 ]; then
			stop
		fi
		if [ ${next} = 1 ]; then
			stop
			next
			play_song
		fi
		if [ ${prev} = 1 ]; then
			stop
			prev
			play_song
		fi
	fi
done

exit 0
